In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("All libraries loaded successfully ✓")
print(f"Pandas version: {pd.__version__}")

All libraries loaded successfully ✓
Pandas version: 2.3.3

In [2]:
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.float_format', lambda x: '%.2f' % x)
pd.set_option('display.max_columns', 25)

from pathlib import Path

DATA_PATH = Path("../data") / "superstore.csv"
df = pd.read_csv(DATA_PATH, encoding="latin-1")

print(f"Dataset loaded: {df.shape[0]:,} rows × {df.shape[1]} columns")
df.head(3)

Dataset loaded: 9,994 rows × 21 columns

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87

In [3]:
import os
print(os.getcwd())

C:\Users\Pranjal Shah\ecommerce-analytics\notebooks

In [4]:
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.float_format', lambda x: '%.2f' % x)
pd.set_option('display.max_columns', 25)

df = pd.read_csv(r'C:\Users\Pranjal Shah\ecommerce-analytics\data\superstore.csv', encoding='latin-1')

print(f"Dataset loaded: {df.shape[0]:,} rows × {df.shape[1]} columns")
df.head(3)

Dataset loaded: 9,994 rows × 21 columns

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87

In [5]:
import os

# List everything inside your data folder
data_path = r'C:\Users\Pranjal Shah\ecommerce-analytics\data'
print(os.listdir(data_path))

['superstore.csv', 'superstore_clean.csv']

In [6]:
import os
data_path = r'C:\Users\Pranjal Shah\ecommerce-analytics\data'
print(os.listdir(data_path))

['superstore.csv', 'superstore_clean.csv']

In [7]:
df = pd.read_csv(r'C:\Users\Pranjal Shah\ecommerce-analytics\data\superstore.csv', encoding='latin-1')

print(f"Dataset loaded: {df.shape[0]:,} rows × {df.shape[1]} columns")
df.head(3)

Dataset loaded: 9,994 rows × 21 columns

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87

In [8]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date']  = pd.to_datetime(df['Ship Date'])

print("Date types after conversion:")
print(df[['Order Date', 'Ship Date']].dtypes)
print(f"\nDate range: {df['Order Date'].min().date()} → {df['Order Date'].max().date()}")
print(f"Dataset spans {df['Order Date'].dt.year.nunique()} years of data")

Date types after conversion:
Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

Date range: 2014-01-03 → 2017-12-30
Dataset spans 4 years of data

In [9]:
df['Profit Margin %'] = (df['Profit'] / df['Sales'] * 100).round(2)
df['Days to Ship']    = (df['Ship Date'] - df['Order Date']).dt.days
df['Year']            = df['Order Date'].dt.year
df['Month']           = df['Order Date'].dt.month
df['Month Name']      = df['Order Date'].dt.strftime('%b')
df['YearMonth']       = df['Order Date'].dt.to_period('M')

def discount_bucket(d):
    if d == 0:       return '0% — No Discount'
    elif d <= 0.10:  return '1–10%'
    elif d <= 0.20:  return '11–20%'
    elif d <= 0.30:  return '21–30%'
    else:            return '30%+'

df['Discount Bucket'] = df['Discount'].apply(discount_bucket)

print("Derived metrics added ✓")
print(f"New columns added: {['Profit Margin %', 'Days to Ship', 'Year', 'Month', 'YearMonth', 'Discount Bucket']}")

Derived metrics added ✓
New columns added: ['Profit Margin %', 'Days to Ship', 'Year', 'Month', 'YearMonth', 'Discount Bucket']

In [10]:
text_cols = ['Segment', 'Category', 'Sub-Category', 'Region', 'Ship Mode', 'State', 'City']

for col in text_cols:
    df[col] = df[col].str.strip().str.title()

print("Text columns standardized ✓")
for col in ['Segment', 'Category', 'Region', 'Ship Mode']:
    print(f"\n{col}: {sorted(df[col].unique())}")

Text columns standardized ✓

Segment: ['Consumer', 'Corporate', 'Home Office']

Category: ['Furniture', 'Office Supplies', 'Technology']

Region: ['Central', 'East', 'South', 'West']

Ship Mode: ['First Class', 'Same Day', 'Second Class', 'Standard Class']

In [11]:
print("=== BUSINESS SANITY CHECKS ===")

neg_sales = df[df['Sales'] <= 0]
print(f"Orders with zero/negative Sales: {len(neg_sales)}")

neg_profit = df[df['Profit'] < 0]
print(f"Loss-making order lines: {len(neg_profit):,} ({len(neg_profit)/len(df)*100:.1f}% of all orders)")
print(f"Total profit destroyed: ${neg_profit['Profit'].sum():,.0f}")

print(f"\nAverage days to ship: {df['Days to Ship'].mean():.1f} days")
print(f"Shipping time range: {df['Days to Ship'].min()}–{df['Days to Ship'].max()} days")

=== BUSINESS SANITY CHECKS ===
Orders with zero/negative Sales: 0
Loss-making order lines: 1,871 (18.7% of all orders)
Total profit destroyed: $-156,131

Average days to ship: 4.0 days
Shipping time range: 0–7 days

In [12]:
df.to_csv(r'C:\Users\Pranjal Shah\ecommerce-analytics\data\superstore_clean.csv', index=False)

print("=== CLEANING COMPLETE ✓ ===")
print(f"Clean dataset saved")
print(f"Final shape: {df.shape[0]:,} rows × {df.shape[1]} columns")

=== CLEANING COMPLETE ✓ ===
Clean dataset saved
Final shape: 9,994 rows × 28 columns

In [13]:
print("=== FINAL DATASET SUMMARY ===")th
print(f"Total rows: {df.shape[0]:,}")
print(f"Total columns: {df.shape[1]}")
print(f"\nColumn list:")
print(list(df.columns))
print(f"\nSample of new derived columns:")
df[['Order Date', 'Profit Margin %', 'Days to Ship', 'Discount Bucket', 'Year']].head(5)

=== FINAL DATASET SUMMARY ===
Total rows: 9,994
Total columns: 28

Column list:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Profit Margin %', 'Days to Ship', 'Year', 'Month', 'Month Name', 'YearMonth', 'Discount Bucket']

Sample of new derived columns:

  Order Date  Profit Margin %  Days to Ship   Discount Bucket  Year
0 2016-11-08            16.00             3  0% — No Discount  2016
1 2016-11-08            30.00             3  0% — No Discount  2016
2 2016-06-12            47.00             4  0% — No Discount  2016
3 2015-10-11           -40.00             7              30%+  2015
4 2015-10-11            11.25             7            11–20%  2015